ft2232: Fix build error
The statement assigned the variable to itself, raising a warning with
clang as shown below. As warnings are promoted to errors with -Werror by
default, this caused the build to fail.

ft2232.c:1514:7: error: explicitly assigning a variable of type 'int' to itself [-Werror,-Wself-assign]
        trst = trst;
        ~~~~ ^ ~~~~
1 error generated.

Change-Id: I16fd20936f00d7ff82962f4fcc629ff434aa4dce
Signed-off-by: Rainer Müller <raimue@codingfarm.de>