flash/nor/esirisc: Rename 'PAGE_SIZE' #define
On Windows (MSYS2/MinGW), 'PAGE_SIZE' is already defined in
limits.h. The error message is the following:

../src/flash/nor/esirisc_flash.c:95:0: error: "PAGE_SIZE" redefined [-Werror]
 #define PAGE_SIZE   4096

In file included from /usr/lib/gcc/x86_64-pc-msys/7.4.0/include-fixed/limits.h:194:0,
                 from /usr/lib/gcc/x86_64-pc-msys/7.4.0/include-fixed/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-pc-msys/7.4.0/include-fixed/limits.h:34,
                 from /usr/include/sys/param.h:12,
                 from ../src/helper/system.h:75,
                 from ./config.h:335,
                 from ../src/flash/nor/esirisc_flash.c:21:
/usr/include/limits.h:223:0: note: this is the location of the previous definition
 #define PAGE_SIZE PAGESIZE

Use 'ESIRISC_PAGE_SIZE' as name to avoid the conflict.

Change-Id: I187db689b1867b28c6076a1370120b548e08daa8
Signed-off-by: Marc Schink <openocd-dev@marcschink.de>