contrib/itmdump: fix compiler warning
Fix the following compiler warning by adding the missing stdlib.h
include.

itmdump.c: In function ‘main’:
itmdump.c:390:16: warning: implicit declaration of function ‘atoi’ [-Wimplicit-function-declaration]
    dump_swit = atoi(optarg);
                ^

Change-Id: I146625bc62a01b2d9bf86d367fb39e4ce3280fcc
Signed-off-by: Colin Baumgarten <colin.baumgarten@gmail.com>