command: print BUG warning when usage is missing
These error messages will prompt patches to be submitted for missing
.usage fields. All of the below must be resolved before next release.

Updates to this patch in Gerrit to fix problems below are most
welcome. Anyone can push updated versions of a patch to Gerrit. If
there are no further updates to this patch within a week, it will be
pushed to the master branch to prompt more fixes.

These were caught by launching OpenOCD.

Error: BUG: command 'command' does not have the '.usage' field filled out
Error: BUG: command 'script' does not have the '.usage' field filled out
Error: BUG: command 'power_restore' does not have the '.usage' field filled out
Error: BUG: command 'srst_deasserted' does not have the '.usage' field filled out
Error: BUG: command 'measure_clk' does not have the '.usage' field filled out
Error: BUG: command 'version' does not have the '.usage' field filled out
Error: BUG: command 'noinit' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'add_script_search_dir' does not have the '.usage' field filled out
Error: BUG: command 'exit' does not have the '.usage' field filled out
Error: BUG: command 'shutdown' does not have the '.usage' field filled out
Error: BUG: command 'gdb_sync' does not have the '.usage' field filled out
Error: BUG: command 'transport' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'list' does not have the '.usage' field filled out
Error: BUG: command 'adapter_name' does not have the '.usage' field filled out
Error: BUG: command 'interface_list' does not have the '.usage' field filled out
Error: BUG: command 'target' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'current' does not have the '.usage' field filled out
Error: BUG: command 'types' does not have the '.usage' field filled out
Error: BUG: command 'names' does not have the '.usage' field filled out
Error: BUG: command 'count' does not have the '.usage' field filled out
Error: BUG: command 'flash' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'banks' does not have the '.usage' field filled out
Error: BUG: command 'list' does not have the '.usage' field filled out
Error: BUG: command 'nand' does not have the '.usage' field filled out
Error: BUG: command 'drivers' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'pld' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'mflash' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'dummy' does not have the '.usage' field filled out
Error: BUG: command 'foo' does not have the '.usage' field filled out
Error: BUG: command 'scan_chain' does not have the '.usage' field filled out
Error: BUG: command 'jtag' does not have the '.usage' field filled out
Error: BUG: command 'init' does not have the '.usage' field filled out
Error: BUG: command 'arp_init' does not have the '.usage' field filled out
Error: BUG: command 'arp_init-reset' does not have the '.usage' field filled out
Error: BUG: command 'names' does not have the '.usage' field filled out
Error: BUG: command 'flush_count' does not have the '.usage' field filled out
Error: BUG: command 'flush_count' does not have the '.usage' field filled out
Error: BUG: command 'arm' does not have the '.usage' field filled out
Error: BUG: command 'reg' does not have the '.usage' field filled out
Error: BUG: command 'etm' does not have the '.usage' field filled out
Error: BUG: command 'arm7_9' does not have the '.usage' field filled out
Error: BUG: command 'at91eb40a.cpu' does not have the '.usage' field filled out
Error: BUG: command 'eventlist' does not have the '.usage' field filled out
Error: BUG: command 'curstate' does not have the '.usage' field filled out
Error: BUG: command 'arp_examine' does not have the '.usage' field filled out
Error: BUG: command 'arp_halt_gdb' does not have the '.usage' field filled out
Error: BUG: command 'arp_poll' does not have the '.usage' field filled out
Error: BUG: command 'arp_reset' does not have the '.usage' field filled out
Error: BUG: command 'arp_halt' does not have the '.usage' field filled out
Error: BUG: command 'arp_waitstate' does not have the '.usage' field filled out
Error: BUG: command 'arm' does not have the '.usage' field filled out
Error: BUG: command 'reg' does not have the '.usage' field filled out
Error: BUG: command 'etm' does not have the '.usage' field filled out
Error: BUG: command 'arm7_9' does not have the '.usage' field filled out
Error: BUG: command 'target_request' does not have the '.usage' field filled out
Error: BUG: command 'trace' does not have the '.usage' field filled out
Error: BUG: command 'fast_load' does not have the '.usage' field filled out
Error: BUG: command 'profile' does not have the '.usage' field filled out
Error: BUG: command 'soft_reset_halt' does not have the '.usage' field filled out

Change-Id: I2c3e529530a15d2295a1950ffc59e8f2fc661012
Signed-off-by: Øyvind Harboe <oyvind.harboe@zylin.com>