remote_bitbang: fix FTBFS on ARM due to alignment issues
This fixes the following error:
remote_bitbang.c:166:19: error: cast increases required alignment of target type [-Werror=cast-align]

Compile-tested only.

Change-Id: I1b8bf27e722a65c29fd55d6668537cfeaed4b352
Signed-off-by: Paul Fertser <fercerpav@gmail.com>