lpcspifi: Add SWD support for LPC43xx
Since JTAG and SWD modes use different IDCODEs, the flash driver complains:

  Error: Device ID 0x2ba01477 is not known as SPIFI capable
  Error: auto_probe failed

Fix this by adding a new target device array entry for the SWD IDCODE,
otherwise duplicating the existing JTAG line.

Tested with LPC4357 and LPC4370.

Change-Id: Ic230e3e989a3e1f1a5b3bae68bdb34e5ef55d392
Signed-off-by: Andreas Färber <afaerber@suse.de>